/** First-run pantry seed: standard Czech-household staples (spec.md "Pantry"). */
export const DEFAULT_PANTRY: string[] = [
  'sůl',
  'pepř',
  'cukr',
  'hladká mouka',
  'polohrubá mouka',
  'rýže',
  'těstoviny',
  'brambory',
  'cibule',
  'česnek',
  'slunečnicový olej',
  'olivový olej',
  'máslo',
  'vejce',
  'mléko',
  'ocet',
  'hořčice',
  'kečup',
  'sójová omáčka',
  'sladká paprika',
  'kmín',
  'majoránka',
  'bobkový list',
  'vegeta',
];
